### ISSUE TITLE
Scripts fallan

### ISSUE THREAD

**Issue by fnandoleal** [bsjaramillo/sb0t#1]
Esta versión impide que algunos scripts se ejecuten correctamente. En la versión 5.42 todos los scripts funcionan correctamente. Hay algún error al leer un archivo de texto que existe dentro de la carpeta de datos de algunos scripts.

**Comment by bsjaramillo** [comment]
Había un error en la v5.43 para leer archivos pero fue corregido en la v5.43.1, puedes especificar que error es ? Que tipo de archivo es y como es el contenido del mismo ?
